<style>
    .list-group-item {
        list-style: none;
    }
</style>
<div class="container">
    <div class="row">
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                <h3 class="panel-title">
                    Recent Comments</h3>
                <!-- <span class="label label-info">
                    78</span> -->
            </div>
            <div class="panel-body">
                <ul class="list-group">
                <?php 
                    foreach($block->getAllQuestion() as $key => $val){
                        if($val->getProductId() == $block->getCurrentProduct()->getId())
                        {
                        
                ?>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <!-- <img src="http://placehold.it/80" class="img-circle img-responsive" alt="" /></div> -->
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="http://www.jquery2dotnet.com/2013/10/google-style-login-page-desing-usign.html">
                                        <?php echo $val->getFirstname().' '.$val->getLastname();?></a>
                                    <!-- <div class="mic-info">
                                        By: <a href="#">Bhaumik Patel</a> on 2 Aug 2013
                                    </div> -->
                                </div>
                                <div class="comment-text">
                                   <?php echo $val->getContent();?> 
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary btn-xs btn-answer" data-id="<?php echo $val->getId();?>" title="Answer">
                                        <span class="glyphicon glyphicon-pencil">Answer</span>
                                    </button>
                                    <button type="button" class="btn btn-success btn-xs btn-edit" title="Approved">
                                        <span class="glyphicon glyphicon-ok"></span>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </div>
                                <div class="form-action">
                                
                                </div>
                                
                            </div>
                        </div>
                    </li>
                <?php
                        }
                        
                    }
                ?>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php
    if($block->isLoggedIn() == true )
    {
        ?>
        <form method='post' class="form-question">
        <input type="hidden" name="url" value="<?= $block->getCurrentUrl();?>"/>
        <input type="hidden" name="product_id" value="<?= $block->getCurrentProduct()->getId();?>"/>
            <div class="form-group">
                <label for="name">Câu hỏi</label>
                <input type="textarea" class="form-control" id="comment" placeholder="Enter a question" name="question"/>
            </div>
            <button type="submit" class="btn btn-primary btn-question" >Submit</button>
        </form>
        <?php
        
    }
    else {
        echo "Vui lòng đăng nhập để đặt câu hỏi";
    }

?>
<div id="ajaxresponse"></div>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            $(".btn-answer").click(function(){
                var id =parseInt( $(this).data('id'));
                var url = "<?php echo $this->getUrl().'question/ajax/answer'?>";
                // alert(url);
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: {
                        id: id,
                    },
                complete: function(response) {         
                    // console.log(response);    
                    // alert(response);
                    // $('#test').removeClass('hideme');
                    //             var html = template('#test', {posts:data}); 
                    //             $('#test').html(html);
                    $('#ajaxresponse').html(data.output);
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
                
                
            });
            jQuery(".form-question").submit(function(e){
                e.preventDefault();
                var content = jQuery('input[name="question"]').val();
                var product_id = jQuery('input[name="product_id"]').val();
                var url = "<?php echo $this->getUrl().'question/ajax/question'?>";
                // alert(product_id);
                jQuery.ajax({
                    url: url,
                    type: 'POST',
                    showLoader: true,
                    cache: false,
                    data: {
                        content: content,
                        product_id: product_id
                    },
                    success: function(response) {         
                        console.log(response);    
                        alert(response);
                        alert('ok');
                    },
                    error: function (xhr, status, errorThrown) {
                        alert('Error happens. Try again.');
                    }

                });
            });
            
        });
    });
</script>

<!-- <div id='test' class="hideme">
    <select>
    <% _.each(posts, function(text,value) { %>
        <option value="<%= value %>"><%= text %></option>
    <% }) %> 
    </select>
</div> -->
