<?php
namespace AHT\Question\Block\Ajax;
 
use Magento\Framework\View\Element\Template;
 
class Answer extends Template
{
  public function __construct(Template\Context $context, array $data = [])
    {
        parent::__construct($context, $data);
    }
 
  protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
 
  public function getProducts($productId)
  {
     return $productId;
  }
}