<?php 
    // var_dump($block->getData('data')['content']);
?>
<form method='post' class="form-edit">
        <input type="hidden" name="id" value="<?= $block->getData('data')['id'];?>"/>
        <input type="textarea" class="form-control" id="comment" value="<?= $block->getData('data')['content'];?>" name="question"/>
        <button type="submit" class="btn btn-primary btn-question" >Lưu</button>
        <button type="button" class="btn btn-primary btn-cancel" >Hủy</button>
</form>